baseURL = "http://example.org/"
languageCode = "en-us"
title = "Walldev"
theme = "hugo-coder"

paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true



[params] # theme parameters
    author = "Muhammad Awaluddin" # author's name
    info = "Product Manager" # author's job title or info
    description = "Awal's personal website" # site description
    keywords = "blog,developer,personal" # site keywords
    avatarURL = "images/wall.png"
    favicon = "/images/favicon-32x32.png"

    # wether you want to hide copyright and credits in the footer
    hideCredits = false
    hideCopyright = false

    colorScheme = "auto"
    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false
    # Series see also post count

    

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 1
    url = "https://github.com/muhawaluddin/"
[[params.social]]
    name = "Twitter"
     icon = "fa fa-2x fa-twitter"
    weight = 2
    url = "https://twitter.com/walldev_?t=LAbThk9DCKeA7J0Aowr2kA&s=09"
[[params.social]]
    name = "Youtube"
    icon = "fa fa-2x fa-youtube"
    weight = 3
    url = "https://www.youtube.com/channel/UCMQYCc8eY7mLB8-7y_l2xfA"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "Post"
    weight = 2
    url = "/post/"
[[menu.main]]
    name = "Project"
    weight = 3
    url = "content/walldev.md"